"""empty message

Revision ID: 2474872f39a6
Revises: 
Create Date: 2024-06-12 06:25:25.580054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2474872f39a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_class', sa.String(length=80), nullable=True),
    sa.Column('man_class', sa.String(length=100), nullable=True),
    sa.Column('count_ill', sa.Integer(), nullable=True),
    sa.Column('count_class', sa.Integer(), nullable=True),
    sa.Column('proc_ill', sa.Integer(), nullable=True),
    sa.Column('closed', sa.Boolean(), nullable=True),
    sa.Column('date_closed', sa.Date(), nullable=True),
    sa.Column('date_open', sa.Date(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_class')
    )
    op.create_table('DataSends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_send', sa.Date(), nullable=True),
    sa.Column('count_all_ill', sa.Integer(), nullable=True),
    sa.Column('count_all', sa.Integer(), nullable=True),
    sa.Column('count_class_closed', sa.Integer(), nullable=True),
    sa.Column('count_ill_closed', sa.Integer(), nullable=True),
    sa.Column('count_all_closed', sa.Integer(), nullable=True),
    sa.Column('sending', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date_send')
    )
    op.create_table('dish',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('recipe', sa.Integer(), nullable=True),
    sa.Column('out_gramm', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.Column('protein', sa.Integer(), nullable=True),
    sa.Column('fats', sa.Integer(), nullable=True),
    sa.Column('carb', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=80), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login'),
    sa.UniqueConstraint('password')
    )
    op.create_table('menu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_menu', sa.Date(), nullable=True),
    sa.Column('type', sa.String(length=80), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('dish_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dish_id'], ['dish.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date_menu')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('menu')
    op.drop_table('users')
    op.drop_table('dish')
    op.drop_table('DataSends')
    op.drop_table('Classes')
    # ### end Alembic commands ###
